### PR TITLE
Issue #3: facilitate remote uris not ending with '.git'

### PR DESCRIPTION
**Pull request by lxmonk**
suggested fix

### CODE REVIEW

**Comment by lxmonk** [comment]
the diff from master better seen in the "Files Changed" tab.

**Comment by ghost** [comment]
@stuarthalloway yes you can append ?w=1

EDIT: hmm it autochanged my link: github.com/Datomic/codeq/pull/4/files?w=1

**Comment by lxmonk** [comment]
sorry, I thought this was already pulled.

**Comment by iNecas** [comment]
Interesting thing: calling `git remote show -n origin` on a repo without remote gives me:

```
* remote origin
  Fetch URL: origin
  Push  URL: origin
  HEAD branch: (not queried)
  Local ref configured for 'git push' (status not queried):
    (matching) pushes to (matching)
```

so the code uses "origin" as the url and continues without complains. On the other hand, if the uri ends with '/', such as 'git@github.com:Datomic/codeq.git/', it fails.

**Pull request merged**
